# Site settings
title: Peter Richmond
email: peter.h.richmond@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for things revolving around the technology that runs the web!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://peripheral1994.github.io" # the base hostname & protocol for your site
twitter_username: peripheral1994
github_username:  peripheral1994

# Build settings
markdown: kramdown
